#lang planet neil/sicp
;;error
(define (cont-frac f g k)
 (if (= k 1) (/ (f k) (g k)) (/ (f k) (+ (g k) (cont-frac f g (- k 1))))
 )
)
(define (c-f N D k)
  (define (cf i)
    (if (= k i)
        (/ (N k) (D k))
        (/ (N i)
           (+ (D i) (cf (+ i 1))))
        )
    )
  (cf 1)
  )
(define (getD x)
  (if (= (remainder (+ x 1) 3) 0) (* (/ (+ x 1) 3) 2) 1)
    )
(+ 2.0 (c-f (lambda (i) 1.0) getD 1000))