#lang planet neil/sicp
(define (make-mobile left right)
  (list left right))
(define (make-branch length structure)
  (list length structure))
;; a)
(define (left-branch x)
  (car x))
(define (right-branch x)
  (cadr x))
(define (branch-length branch)
  (car branch))
(define (branch-structure branch)
  (cadr branch))
;; b)
(define (total-weight s)
  (define (weight-iter structure)
    (cond 
      ((not (pair? structure)) structure)
      ((pair? structure) (+ (weight-iter (branch-structure (left-branch structure)) (weight-iter (branch-structure (right-branch branch-structure))))))
      ))
  (+ (weight-iter (branch-structure (left-branch s)) (branch-structure (weight-iter (right-branch s))))
))
;; c)
(define (force-length b)
  (* (total-weight (branch-structure b) (branch-length b))))
(define (balance structure)
    (if (and (pair? (left-branch structure)) (pair? (right-branch structure))) 
        (and (balance (branch-structure (left-branch structure))) (balance (branch-structure (right-branch structure)))) 
        (= (force-length (left-branch structure)) (force-length (right-branch structure)))
        )
  )

;; d) 修改right-branch 和 branch-structure 即可