#lang planet neil/sicp
(define (square x)(* x x))
(define (tree-map tree factor)
  (map (lambda (sub-tree)
         (if (pair? sub-tree) 
             (square-tree-map sub-tree)
             (factor sub-tree)
             )
         ) tree))
(define (square-tree-map tree)
  (tree-map tree square))
(square-tree-map (list 1 (list 2 (list 3 4) 5)(list 6 7)))