#lang planet neil/sicp

(define tolerance 0.00001)
(define (fixed-point f first-guess)
  (define (close-enough? v1 v2)
    (< (abs (- v1 v2)) tolerance))
  (define (try guess)
    (newline)
    (display guess)
    (let ((next (f guess)))
      (if (close-enough? guess next)
          next
          (try next)
      ))
  )
  (try first-guess)
  )
(define (log-produce)
  (fixed-point (lambda (x)(/ (log 1000) (log x))) 2.0))
(define (average-damp f)
  (lambda (x) (average (f x) x)))
(define (average a b)
  (/ (+ a b) 2))
(log-produce)
(newline)
(fixed-point (average-damp (lambda (x)(/ (log 1000) (log x)))) 2.0)