#lang racket
(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount)) 
               balance)
        "Insufficient funds"))
  (define (failed amount)
    "Incorrect password")
  (define (deposit amount)
    (set! balance (+ balance amount)))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          ((eq? m 'failed) failed)
          (else (error "Unknown request -- MAKE-ACCOUNT" m))))
  (lambda (x y) 
    (if (eq? password x)
        (dispatch y)
        (dispatch 'failed)
        )))

(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 40)
((acc 'some-other-password 'deposit) 50)